version: 2.1

jobs:
  jahia-cli-node-latest: &jahia-cli-test
    docker:
      - image: circleci/node:latest-browsers
    environment:
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
    working_directory: ~/jahia-cli
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-jahia-cli-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
            - v1-npm-jahia-cli-{{checksum ".circleci/config.yml"}}
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Linting
          command: yarn lint
      - run:
          name: Display version
          command: ./bin/run --version
      - run:
          name: Display help
          command: ./bin/run --help
      - persist_to_workspace:
          root: .
          paths: .

  jahia-cli-node-12:
    <<: *jahia-cli-test
    docker:
      - image: circleci/node:12-browsers

  jahia-cli-cache:
    <<: *jahia-cli-test
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          key: v1-yarn-jahia-cli-{{checksum ".circleci/config.yml"}}-{{checksum "jahia-cli/yarn.lock"}}
          paths:
            - ~/jahia-cli/node_modules
            - /usr/local/lib/node_modules

  # Publish a new version of the jahia-cli to NPM
  npm-publish:
    docker:
      - image: circleci/node:latest-browsers
    environment:
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
    working_directory: ~/jahia-cli
    steps:
      - checkout
      #      - attach_workspace:
      #          at: /tmp/workspace
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Install Typescript
          command: npm -g install typescript
      - run:
          name: Install oclif-dev
          command: npm -g install @oclif/dev-cli
      - run:
          name: Authenticate with NPM registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Updating NPM version with GitHub tag
          command: |
            IMAGE_TAG=${CIRCLE_TAG/v/''}
            echo "Image tag is: $IMAGE_TAG"
            npm --no-git-tag-version version $IMAGE_TAG
      - run:
          name: Build the typescript app
          command: tsc -b
      - run:
          name: Generate the oclif manifest
          command: oclif-dev manifest
      - run:
          name: Update the oclif readme
          command: oclif-dev readme
      #      - run:
      #          name: Purge oclif.manifest.json
      #          command: rm -f oclif.manifest.json
      - run:
          name: Ls jahia-cli content
          command: ls -lah ./
      - run:
          name: Publish to NPM registry
          command: npm publish

  # Test the package that was just published to npm
  npm-test:
    docker:
      - image: node:latest
    working_directory: ~/jahia-cli-npm
    steps:
      - run:
          name: Install
          command: npm install -g jahia-cli
      - run:
          name: Display version
          command: jahia-cli --version
      - run:
          name: Display help
          command: jahia-cli --help

  jahia-cli-integration-tests:
    docker:
      - image: circleci/node:latest-browsers
      - image: jahia/jahia-dev:latest
    #environment:
    #  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          keys:
            - v1-npm-jahia-cli-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
            - v1-npm-jahia-cli-{{checksum ".circleci/config.yml"}}
      - run:
          name: Install jahia-cli
          command: sudo npm install -g jahia-cli
      - run:
          name: Check jahia-cli help
          command: jahia-cli --help
      #      - run:
      #          name: Run Jahia docker (latest)
      #          command: docker run -p 8080:8080 -d jahia/jahia-dev:latest
      - run:
          name: Wait for Jahia to be alive
          command: jahia-cli alive
      - run:
          name: Generate a default manifest
          command: jahia-cli manifest:create --filepath=/tmp/manifest.yml
      - run:
          name: Loading the assets from the default manifest
          command: jahia-cli assets:load --manifest=/tmp/manifest.yml
      - run:
          name: Loading the assets from the default manifest
          command: jahia-cli modules:batch --manifest=/tmp/manifest.yml

workflows:
  version: 2
  build-npm:
    jobs:
      - npm-publish:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - npm-test:
          requires:
            - npm-publish
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
  lint-and-test:
    jobs:
      - jahia-cli-node-latest
      - jahia-cli-node-12
      - jahia-cli-integration-tests
      - jahia-cli-cache:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
